#ESTE É UM TIPO DE EXPRESSÃO QUE RETORNA UM VALOR BOOL
aula=10>5

aula="CFB Cursos"

print(bool(aula))
# AQUI NÓS CONSEGUIMOS AVALIAR SE TEM ALGO LÁ DENTRO

# PODEMOS CONFERIR SE HÁ ALGO EM UMA STRING MESMO SEM SER BOOL
if aula:
    print("Possui texto")
else: 
    print("Vazio")

# QUALQUER VALOR OU TEXTO(LENGTH) DIFERENTE DE 0 SERÁ RETORNADO TRUE