canal="CFP Cursos"
curso="Cursos de python"
print(canal + " - " + curso)

# PARA COMENTÁRIOS: USAR O HASTAG
"""
COMENTÁRIO DE MULTIPLAS LINHAS
"""
# A QUEBRA DE LINHA DE COMANDO PADRÃO É O ENTER, PORÉM PODE SER USADO O PONTO E VIRGULA

if 10>2:
    print("teste if")
print("fim")

# PARA IFS, NÃO TEM CHAVES, APENAS DOIS PONTOS, E TUDO QUE PERTENCER AO IF TEM QUE TER O MESMO
# ESPAÇAMENTO, APÓ0S QUEBRÁ-LO, DECLARAMOS O FIM DO CÓDIGO DENTRO DO IF